### PR TITLE
Update chainlink contracts

### PR DESCRIPTION
**Pull request by lyubenkov**

### CODE REVIEW

**Comment by lyubenkov** [comment]
Passed here http://neon-test-allure.s3-website.eu-central-1.amazonaws.com/basic/devnet/NDEV-1724/1466/#suites/81ea48a407543318f67f098ee2e5c6c7/5aa2a8c2a8c5e010/

**Review by gigimon — APPROVED** [review]

**Comment by gigimon** [comment]
@lyubenkov fix conflicts and show green build :)

**Comment by lyubenkov** [comment]
@gigimon green build is there: https://github.com/neonlabsorg/neon-tests/actions/runs/8060981328

**Comment by gigimon** [comment]
> @gigimon green build is there: https://github.com/neonlabsorg/neon-tests/actions/runs/8060981328

@lyubenkov run it on devnet, because oracles work only on devnet

**Comment by lyubenkov** [comment]
> @lyubenkov run it on devnet, because oracles work only on devnet

Devnet build passed too! https://github.com/neonlabsorg/neon-tests/actions/runs/8061598807

**Pull request merged**
